services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - MONGODB_URL=${MONGODB_URL}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - MODEL_NAME=${MODEL_NAME}
      - DISTANCE_THRESHOLD_SMALL=${DISTANCE_THRESHOLD_SMALL}
      - DISTANCE_THRESHOLD_MEDIUM=${DISTANCE_THRESHOLD_MEDIUM}
      - DISTANCE_THRESHOLD_LARGE=${DISTANCE_THRESHOLD_LARGE}
      - SECRET_KEY=${SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - GMAIL_SENDER_EMAIL=${GMAIL_SENDER_EMAIL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge